// manifest.ts — GENERATED by scripts/gen-starter-skills.mjs. Do not edit by hand.
// Edit the SKILLS array in the generator and re-run `node scripts/gen-starter-skills.mjs`.
//
// The 30 starter Skills shipped in the AI Office Launch Kit (PA-STARTERSKILL-1..6). The `body` is the
// SKILL.md technique copied verbatim into the owner's brain at seed time; the metadata drives
// tier-gating (lib/skills/resolve.ts) and the Starter Pack surface.

export type StarterSkillTier = "free" | "pro_plus" | "studio_plus" | "enterprise";
export type StarterSkillCategory =
  | "voice_style"
  | "email_drafting"
  | "sales"
  | "research"
  | "operations"
  | "decision_shape";

export type StarterSkillRecord = {
  slug: string;
  name: string;
  description: string;
  whenToUse: string;
  tierRequired: StarterSkillTier;
  category: StarterSkillCategory;
  prerequisites: string[];
  /** The SKILL.md technique body (markdown), copied into the brain verbatim at seed time. */
  body: string;
};

export const STARTER_SKILL_MANIFEST: readonly StarterSkillRecord[] = [
  {
    "slug": "write-like-the-user",
    "name": "Write Like the Owner",
    "description": "Pull the owner's voice from their past writing and mirror its cadence and word choices instead of defaulting to generic prose.",
    "whenToUse": "Any time you draft something the owner will send under their own name — email, post, proposal, reply. Skip it for internal scratch notes nobody reads.",
    "tierRequired": "free",
    "category": "voice_style",
    "prerequisites": [],
    "body": "# Write Like the Owner\n\nThe fastest way to sound like the owner is to read three things they already wrote and copy the moves. Don't invent a voice — find the one that's already in the brain and match it.\n\n## The technique\n\n- Before drafting, pull 2–3 real examples the owner wrote — a past email, a note, a post. The brain has them.\n- Read for the moves, not the topic: sentence length, how they greet, whether they use first names, where they put the ask.\n- Match the cadence. If they write short and blunt, write short and blunt. If they ramble warm, don't clip them into a memo.\n- Reuse their actual words for recurring things — their name for a product, a customer, a service. Don't swap in a synonym.\n- Draft, then read it back against the example. If a sentence sounds like you and not like them, rewrite that sentence.\n\n## Do this, not that\n\n**Do:** Read the owner's last three sent emails, notice they open with just a first name and a dash, and open your draft the same way: \"Mike —\".\n\n**Don't:** Open with \"I hope this email finds you well\" because that's how a generic assistant starts — the owner has never written that sentence in their life.\n\n## Why this works\n\nVoice isn't a setting, it's a pattern you can read off real writing. The owner already proved how they sound every time they hit send. Copying that beats guessing at a tone, and it's why a draft can come back right the first time instead of after three rounds of \"make it sound more like me.\""
  },
  {
    "slug": "lead-with-the-action",
    "name": "Lead With the Action",
    "description": "Put the claim, the finding, or the ask in the first sentence — then explain. Never bury the point in the middle.",
    "whenToUse": "Every draft, every reply, every brief. The longer the piece, the more it matters.",
    "tierRequired": "free",
    "category": "voice_style",
    "prerequisites": [],
    "body": "# Lead With the Action\n\nDeclare before you explain. The first sentence of a paragraph is the point; the next two or three are the why. The reader should know the conclusion by sentence one.\n\n## The technique\n\n- Write the point first. The claim, the answer, the thing you need them to do — sentence one.\n- Put the reasoning after, not before. Context that leads up to a point makes the reader wait; context that follows a point makes sense.\n- If there's an ask, it lives in the first or last sentence — never the middle, never after a hedge.\n- Cut the runway. \"I wanted to reach out because\" and \"After giving this some thought\" are throat-clearing. Delete them and start at the point.\n- Read the first sentence alone. If it doesn't carry the message, you buried it — move the real point up.\n\n## Do this, not that\n\n**Do:** \"The roof passed inspection — we're clear to invoice.\" Then the detail: what was checked, what's next.\n\n**Don't:** \"So I went out this morning and spent some time looking at a few things on the property, and after walking the whole roof and checking the flashing, I think we're probably in good shape to move forward with billing.\"\n\n## Why this works\n\nPeople skim. They read the first sentence of every paragraph and stop when they have what they need. If the point is in the middle, half your readers never reach it. Leading with the action respects that — they get the conclusion immediately and read the why only if they want it."
  },
  {
    "slug": "dont-be-a-chatbot",
    "name": "Don't Sound Like a Chatbot",
    "description": "Cut the assistant filler — \"I'd be happy to,\" \"let me know if there's anything else,\" \"great question\" — that marks writing as machine-made.",
    "whenToUse": "Everything customer-facing, and most internal writing too. The owner is a person talking to a person.",
    "tierRequired": "free",
    "category": "voice_style",
    "prerequisites": [],
    "body": "# Don't Sound Like a Chatbot\n\nThe tells that scream \"an AI wrote this\" are filler phrases no real operator uses. Strip them. What's left is shorter and sounds human.\n\n## The technique\n\n- Kill the eager openers: \"I'd be happy to help with that,\" \"Great question,\" \"Absolutely!\" Start at the answer instead.\n- Kill the trailing offer: \"Let me know if there's anything else I can help with,\" \"Feel free to reach out.\" End on the last real thing.\n- Kill the hedged enthusiasm: \"I'd love to,\" \"happy to,\" \"excited to.\" Say what you'll do, not how you feel about doing it.\n- Drop \"here's what I found\" preambles. State the finding. The reader can see it's an answer.\n- No padded summary at the end. The last sentence is a fact or the next step, not \"Hopefully this helps!\"\n\n## Do this, not that\n\n**Do:** \"Sent the quote. It's $4,200, valid through Friday. Want me to follow up Monday if they're quiet?\"\n\n**Don't:** \"Absolutely, I'd be happy to help with that! I've gone ahead and sent the quote over. Let me know if there's anything else I can assist you with! 😊\"\n\n## Why this works\n\nFiller is the cheapest signal that something was mass-produced. Customers feel it even when they can't name it — the writing sounds like a help desk, not the person they hired. Stripping it costs nothing and makes every message read like a real person who's busy and respects their time."
  },
  {
    "slug": "honest-hedging",
    "name": "Commit, Don't Hedge",
    "description": "Drop the hedge stacks — \"probably,\" \"likely,\" \"might want to consider,\" \"could potentially.\" Commit to the call or say plainly what you don't know.",
    "whenToUse": "Recommendations, follow-ups, decisions, anything where the reader wants a position. Especially when you're tempted to soften.",
    "tierRequired": "free",
    "category": "voice_style",
    "prerequisites": [],
    "body": "# Commit, Don't Hedge\n\nHedging reads as either weakness or evasion. Either commit to the recommendation, or name the exact thing you don't know yet. Both beat a pile of soft words.\n\n## The technique\n\n- Replace the hedge with a position: \"You might want to consider following up\" becomes \"Follow up Thursday.\"\n- When you don't know, say what's missing — not \"probably,\" but \"I don't have their budget yet, so I can't size this.\"\n- Never stack hedges. \"I think it's probably likely that\" is three softeners doing one job badly. Pick zero.\n- \"In practice\" and \"usually\" are honest — they say a pattern holds without overclaiming. Hedge words pretend to knowledge you don't have.\n- Read it back: if you could delete a qualifier and the sentence got stronger and stayed true, delete it.\n\n## Do this, not that\n\n**Do:** \"Their last three jobs all closed within a week of the quote. Send it today; they move fast.\"\n\n**Don't:** \"It seems like they might possibly be the kind of client who could potentially be ready to move forward relatively soon, so it may be worth considering sending something over at some point.\"\n\n## Why this works\n\nThe owner is paying for judgment, not a weather forecast. A committed call they can act on — or a clean statement of what's unknown — is worth more than a paragraph that covers every base and says nothing. Hedging protects the writer and abandons the reader. Commit."
  },
  {
    "slug": "specific-over-generic",
    "name": "Specific Over Generic",
    "description": "Name the person, the dollar amount, the date, the file. Replace \"stakeholders,\" \"soon,\" and \"several\" with the real thing.",
    "whenToUse": "Always. Every claim, every plan, every follow-up. If a real detail exists, use it.",
    "tierRequired": "free",
    "category": "voice_style",
    "prerequisites": [],
    "body": "# Specific Over Generic\n\nSpecificity is the difference between writing that lands and writing that evaporates. If a number, a name, or a date exists, use it. If it doesn't, say so — don't paper over the gap with \"many\" or \"several.\"\n\n## The technique\n\n- Swap vague nouns for real ones: not \"the stakeholders,\" but \"Sarah and the two crew leads.\"\n- Swap vague time for real time: not \"soon\" or \"shortly,\" but \"Thursday\" or \"by the 15th.\"\n- Swap vague quantity for the count: not \"several leads,\" but \"four leads,\" or pull the actual number from the brain.\n- Cite the source inline: the customer's name, the dollar figure, the date of the call. Receipts beat adjectives.\n- When you don't have the specific, name the gap plainly: \"I don't have the close date yet\" — not a fuzzy stand-in.\n\n## Do this, not that\n\n**Do:** \"Patrick paid $3,500 plus monthly hosting; his next invoice is the 1st.\"\n\n**Don't:** \"The client made a significant payment and there are some ongoing costs that will recur periodically.\"\n\n## Why this works\n\nGeneric writing could be about anyone, so it convinces no one. A specific number or name proves you actually know the situation — it's a receipt, not a claim. The owner trusts work that names things, because vagueness is what people hide behind when they don't have the facts."
  },
  {
    "slug": "cold-intro-structure",
    "name": "Cold Intro That Gets a Reply",
    "description": "Open a cold email on the prospect's pain, show the one thing that's different about you, then make a single small ask.",
    "whenToUse": "First-touch outreach to someone who doesn't know the owner. Not for warm leads or existing customers — those get a different open.",
    "tierRequired": "pro_plus",
    "category": "email_drafting",
    "prerequisites": [],
    "body": "# Cold Intro That Gets a Reply\n\nA cold email earns a reply by being about them, not you. Lead with the pain they actually feel, name the one way you're different, and ask for something small enough to say yes to.\n\n## The technique\n\n- Open on their pain in one concrete sentence — the specific problem someone in their seat lives with, not a generic compliment.\n- Skip the company autobiography. They don't care what year you were founded.\n- Name one differentiator, plainly. The single thing you do that the alternative doesn't. One, not five.\n- Make the ask small: a 10-minute call, a yes/no question, a look at one example. Not \"let's set up a meeting to explore synergies.\"\n- Keep it under 120 words. A cold email that needs scrolling gets archived.\n\n## Do this, not that\n\n**Do:** \"Most roofers in town quote off a ladder and a guess. We measure off satellite and hand you the supplement language carriers actually approve. Worth a 10-minute look at one of your open claims?\"\n\n**Don't:** \"We are a full-service, industry-leading provider of innovative roofing solutions committed to excellence. We'd love to schedule a meeting to explore how we can leverage our expertise to add value to your organization.\"\n\n## Why this works\n\nA stranger gives you one sentence before they decide to keep reading or hit delete. Spend it on their problem and they lean in; spend it on your mission statement and they're gone. The small ask works because a busy person will trade ten minutes long before they'll commit to a relationship."
  },
  {
    "slug": "quote-follow-up",
    "name": "Follow Up on a Quote",
    "description": "Re-send the value, not just a nudge — restack what they get and add a real reason the window is closing, without fake urgency.",
    "whenToUse": "A quote or proposal went out and the prospect went quiet. Use after a few days of silence, before they forget the conversation entirely.",
    "tierRequired": "pro_plus",
    "category": "email_drafting",
    "prerequisites": [],
    "body": "# Follow Up on a Quote\n\nA good quote follow-up reminds them what they're getting, not just that you're waiting. Restate the value in their terms, then give one honest reason to decide now.\n\n## The technique\n\n- Don't open with \"just checking in\" — that's a nudge with no value. Open with the outcome they wanted.\n- Restack the value in one tight list: what the price actually includes, framed as what it solves for them.\n- Add one real reason to move now — your calendar fills next month, the material price holds until the 1st, the storm-season window. Real, not invented.\n- Make the next step a single decision: \"reply yes and I'll book the crew,\" not \"let me know your thoughts.\"\n- Keep the door open without groveling. One follow-up that respects them beats five that beg.\n\n## Do this, not that\n\n**Do:** \"Quick recap on the $4,200: that's the full tear-off, new underlayment, and the supplement filed with your carrier — not just shingles on top. I've got a crew slot the week of the 14th; after that it's June. Want me to hold it?\"\n\n**Don't:** \"Hi, just circling back to see if you had any thoughts on the quote I sent. Let me know if you have any questions. Looking forward to hearing from you!\"\n\n## Why this works\n\nBy the time you follow up, they've half-forgotten why the price was worth it. A bare nudge makes them re-justify the whole thing from scratch; restating the value does that work for them. And an honest reason to decide now — a real deadline, not a manufactured one — gives a stalled buyer permission to move without feeling pressured."
  },
  {
    "slug": "customer-reply-tone-match",
    "name": "Match the Customer's Tone",
    "description": "Read the tone of the inbound message — clipped, warm, frustrated, formal — and answer in a register that fits instead of one flat default.",
    "whenToUse": "Replying to any customer or prospect message. Especially when they're upset or unusually casual — a mismatch reads as tone-deaf.",
    "tierRequired": "pro_plus",
    "category": "email_drafting",
    "prerequisites": [],
    "body": "# Match the Customer's Tone\n\nRead how they wrote before you decide how to answer. A frustrated customer needs acknowledgment first; a one-line text gets a one-line reply. Matching the register makes the answer land.\n\n## The technique\n\n- Read the inbound for tone, not just content: word count, punctuation, whether they're warm or clipped, calm or hot.\n- If they're frustrated, lead by naming the problem and owning it — not with a defense and not with forced cheer.\n- If they wrote two casual lines, don't answer with five formal paragraphs. Mirror the length.\n- Stay in the owner's voice while you match their register — match energy, not their exact words or grammar.\n- Never out-escalate. If they're annoyed, you're calm and direct; you don't match anger with anger.\n\n## Do this, not that\n\n**Do:** They wrote: \"Still no invoice. This is the third time I've asked.\" You answer: \"That's on me — sending it in the next five minutes, and I'll confirm once it's in your inbox. Sorry you had to ask three times.\"\n\n**Don't:** Answer that same frustrated message with \"Thank you so much for reaching out! We truly value your business and appreciate your patience. We'll look into this for you!\" — chipper at someone who's mad reads as not listening.\n\n## Why this works\n\nTone is most of the message. The same words land completely differently depending on whether they meet the customer where they are. A frustrated person who gets a cheerful auto-reply feels unheard and gets angrier; one who gets a calm, owning answer feels handled. Reading the register first is how a reply defuses instead of inflames."
  },
  {
    "slug": "subject-line-not-filtered",
    "name": "Subject Lines That Get Opened",
    "description": "Write subject lines that are concrete and specific — a real thing the reader would say out loud — not clickbait and not vague.",
    "whenToUse": "Every email that needs to be opened. Cold outreach, follow-ups, anything competing in a full inbox.",
    "tierRequired": "pro_plus",
    "category": "email_drafting",
    "prerequisites": [],
    "body": "# Subject Lines That Get Opened\n\nA subject line is a promise about what's inside. Make it concrete enough that the reader knows the email is for them, without the clickbait that gets it filtered or ignored.\n\n## The technique\n\n- Be specific: name the thing the email is about — the job, the number, the date — not \"Following up\" or \"Quick question.\"\n- Write it like a sentence the reader would actually say, not a marketing headline.\n- No clickbait, no fake urgency, no all-caps, no \"Don't miss out.\" Those train the reader to ignore you and train filters to bury you.\n- Shorter wins on mobile — the first 4–5 words carry it. Front-load the specific.\n- If the email has one ask or one fact, put it in the subject: \"Crew slot open the week of the 14th.\"\n\n## Do this, not that\n\n**Do:** \"Your supplement got approved — $3,100\"\n\n**Don't:** \"IMPORTANT: Don't miss this exclusive opportunity!!! 🚨\"\n\n## Why this works\n\nThe subject line is the only thing that competes for the open. Vague ones (\"Touching base\") give no reason to click; clickbait ones get the open once and the unsubscribe right after. A concrete, honest subject earns the open and sets up the email to be believed — the reader already knows you don't waste their attention."
  },
  {
    "slug": "boundary-setting-decline",
    "name": "Say No Without Burning the Bridge",
    "description": "Decline a request — a discount, a deadline, an out-of-scope ask — clearly and warmly, so the relationship survives the no.",
    "whenToUse": "When the answer has to be no: a price you won't drop, work you don't do, a timeline you can't hit. Anytime softening into a maybe would make it worse.",
    "tierRequired": "pro_plus",
    "category": "email_drafting",
    "prerequisites": [],
    "body": "# Say No Without Burning the Bridge\n\nA clean no is kinder than a fake maybe. Give the decision plainly, give the one real reason, and offer the door you can hold open — without pretending the answer is yes.\n\n## The technique\n\n- Lead with the no, gently but clearly. Don't bury it under three paragraphs of cushioning that make them think it's a yes.\n- Give one honest reason, not a defensive essay. \"I can't hit Friday and do it right\" beats a paragraph of excuses.\n- Offer the alternative you can actually deliver — a different date, a different scope, a referral. A no with a door beats a no with a wall.\n- Don't apologize five times. One acknowledgment is respect; five is begging.\n- Keep your voice warm. A firm no said warmly keeps the relationship; a mushy maybe said to avoid conflict destroys it later.\n\n## Do this, not that\n\n**Do:** \"I can't take the price below $4,000 — below that I'm cutting corners I won't put my name on. What I can do is split it into two payments if cash flow's the issue. Want me to set that up?\"\n\n**Don't:** \"Hmm, let me see what I can do… I'll try to work something out and get back to you\" — when you already know the answer is no, and the maybe just delays the disappointment and adds a broken promise to it.\n\n## Why this works\n\nPeople respect a clear no and resent a slow one. A fake maybe buys you a few comfortable days and then costs you trust when it turns into a no anyway. Saying it straight, warmly, with a real alternative shows the customer you take the relationship seriously enough to be honest with them — which is exactly why they come back."
  },
  {
    "slug": "lead-qualification",
    "name": "Qualify a Lead Fast",
    "description": "Sort a new lead on fit, pain, budget, and timing so the owner spends time on the ones who'll actually close.",
    "whenToUse": "A new lead comes in and you need to decide how hard to chase it. Use before booking a long call with someone who may never buy.",
    "tierRequired": "pro_plus",
    "category": "sales",
    "prerequisites": [],
    "body": "# Qualify a Lead Fast\n\nQualifying is deciding who deserves the owner's hours. Four reads — are they a fit, do they feel the pain, can they pay, are they ready — tell you whether to chase, nurture, or let go.\n\n## The technique\n\n- Fit: are they the kind of customer the owner serves well? Wrong-fit leads cost more than they pay, even when they buy.\n- Pain: do they have the problem badly enough to act? No pain, no purchase — a curious tire-kicker isn't a lead.\n- Budget: can they afford it without a fight? You don't need the exact number, just whether the price will be a shock.\n- Timing: are they ready now, or someday? \"Someday\" goes to nurture, not the calendar.\n- Score it hot / warm / cold and act accordingly — hot gets a call today, warm gets a sequence, cold gets a note and a wait.\n\n## Do this, not that\n\n**Do:** \"They run a 12-truck HVAC shop (fit), said they're losing jobs to slow quotes (pain), didn't blink at the range I floated (budget), and want it before summer (timing). Hot — book the call today.\"\n\n**Don't:** Spend an hour on a discovery call with someone who liked a post, has no specific problem, hasn't mentioned money, and is \"just exploring for now\" — then wonder why it didn't close.\n\n## Why this works\n\nThe owner's time is the scarcest thing in the business, and the fastest way to waste it is treating every lead as equal. Most leads aren't going to buy; a few are. Qualifying up front tells you which is which, so the hours go to the people who'll close instead of the people who'll politely ghost."
  },
  {
    "slug": "objection-handling",
    "name": "Handle the Real Objection",
    "description": "Find the actual objection hiding behind the stated one, then address the fear of loss driving it instead of arguing the surface.",
    "whenToUse": "A prospect pushes back — on price, timing, \"I need to think about it.\" Use before you discount or walk, when there's still a real conversation to have.",
    "tierRequired": "pro_plus",
    "category": "sales",
    "prerequisites": [],
    "body": "# Handle the Real Objection\n\nThe first objection is rarely the real one. \"Too expensive\" usually means \"I'm not sure this is worth it\" or \"I'm scared of getting burned again.\" Surface the real one, then speak to the loss behind it.\n\n## The technique\n\n- Don't take the first objection at face value. \"Too expensive\" compared to what? Ask the question that surfaces the real worry.\n- Listen for loss aversion — most objections are fear of making a wrong call, not the price itself. People dread the loss more than they want the gain.\n- Name the fear out loud: \"Sounds like you've been burned by a contractor before and you don't want to repeat it.\" Naming it defuses it.\n- Answer the real objection, not the stated one. If the fear is being abandoned mid-job, talk about how you stay reachable — not about the price.\n- Don't argue. You're not winning a debate; you're removing the reason they're scared to say yes.\n\n## Do this, not that\n\n**Do:** They say \"it's a lot of money.\" You ask, \"Is it the number, or is it that the last guy took a deposit and disappeared?\" — and now you can actually solve the thing.\n\n**Don't:** Hear \"it's a lot of money\" and immediately drop the price 15% — you just discounted to solve a fear that wasn't about money, left margin on the table, and taught them to push.\n\n## Why this works\n\nPeople rarely tell you the real reason they're hesitating on the first try — partly because they haven't named it themselves. If you answer the surface objection, you solve the wrong problem and they still don't buy. Surfacing the real one, usually a fear of loss, lets you address what's actually in the way — and most of the time it costs you nothing, where a reflexive discount costs margin every time."
  },
  {
    "slug": "discovery-call-note-capture",
    "name": "Capture What Matters From a Call",
    "description": "Log the few things from a discovery call that change the deal — pain, budget signals, decision process, exact words — and skip the transcript.",
    "whenToUse": "After a sales or discovery call, when turning a messy conversation into notes the owner and the next draft can use.",
    "tierRequired": "pro_plus",
    "category": "sales",
    "prerequisites": [],
    "body": "# Capture What Matters From a Call\n\nA discovery call has five useful minutes buried in thirty. Capture the parts that move the deal — what hurts, who decides, what they can spend, the exact phrases they used — and let the rest go.\n\n## The technique\n\n- Log the pain in their words. The exact phrase they used (\"I'm drowning in paperwork\") is gold for the follow-up — quote it back later.\n- Log the decision process: who else signs off, what has to happen before they can say yes, when they need it.\n- Log budget signals — a number, a range, a flinch, a \"we spent X on the last guy.\"\n- Log the one thing they care about most. Every deal has a center of gravity; name it.\n- Skip the play-by-play. Nobody needs \"then we talked about the weather.\" Notes are for what changes the next move.\n\n## Do this, not that\n\n**Do:** \"Pain: 'losing two days a week to invoicing.' Decision: she decides, but her partner Dave has to bless anything over $5k. Budget: paid $6k for a system that didn't work. Cares most about: not having to retrain staff. Wants it live by August.\"\n\n**Don't:** Write a paragraph that recaps the whole call chronologically — \"We started by introducing ourselves, then she told me about her business history…\" — burying the three facts that actually decide the deal.\n\n## Why this works\n\nNotes you can act on beat notes that are complete. A transcript of the whole call is a haystack; the owner needs the needles — the pain, the decision-maker, the budget, the one thing they care about. Capturing the exact words matters because quoting a prospect back to themselves in the follow-up proves you listened, and that's often what closes."
  },
  {
    "slug": "proposal-drafting-framework",
    "name": "Turn Notes Into a Proposal",
    "description": "Build a proposal from messy call notes by leading with their problem, scoping the work in their terms, and pricing it as an outcome.",
    "whenToUse": "After discovery, when the owner needs a proposal or scope of work that actually reflects what the prospect said.",
    "tierRequired": "pro_plus",
    "category": "sales",
    "prerequisites": [],
    "body": "# Turn Notes Into a Proposal\n\nA proposal that wins reflects the call back to them. Open on the problem they described, scope the work as the solution to that problem, and price it against the outcome — not as a parts list.\n\n## The technique\n\n- Open with their problem in their words — proof you were listening, before a single line item.\n- Scope the work as outcomes, then the steps under each. \"Stop losing jobs to slow quotes\" → the system that fixes it. Not a naked feature list.\n- Price against the outcome, not the hours. Anchor to what the problem costs them, so the number reads as a deal.\n- Make the path obvious: what happens first, what you need from them, when it's done. No mystery.\n- One clear next step at the end — sign here, reply yes, book the kickoff. Not three options that stall the decision.\n\n## Do this, not that\n\n**Do:** Open: \"You said you're losing two days a week to invoicing and it's costing you jobs.\" Then scope the fix, price it against the cost of those lost days, and end with \"Reply 'go' and we start Monday.\"\n\n**Don't:** Send a generic template that opens with your company bio and lists features and hourly rates with no connection to anything they said on the call.\n\n## Why this works\n\nA prospect reads a proposal asking one question: does this person understand my problem? Leading with their own words answers yes before you've asked for the sale. Pricing against the outcome reframes the number from a cost to a return — \"$5k to stop losing $2k a week\" sells itself, where the same $5k as a line item invites haggling."
  },
  {
    "slug": "stack-the-deck-close",
    "name": "Restack the Value Before the Ask",
    "description": "Right before the close, line up everything the buyer gets in one stack so the price lands as small against the total — then ask.",
    "whenToUse": "At the moment of decision — the end of a proposal, the close of a call, the upsell page. When the buyer is about to weigh price against value.",
    "tierRequired": "pro_plus",
    "category": "sales",
    "prerequisites": [],
    "body": "# Restack the Value Before the Ask\n\nBefore you name the price, remind them of everything they're getting. Stack the pieces — each a real, specific thing — so the total dwarfs the number, then make the ask. The order is the whole trick.\n\n## The technique\n\n- List the components right before the price, each one concrete: not \"support,\" but \"a same-day answer whenever a job's on the line.\"\n- Make every line a real thing with standalone worth — something the buyer would pay for on its own.\n- Stack the total so it visibly beats the price. The number should feel small against the pile, not the other way around.\n- Name the price once, plainly, right after the stack — not buried, not apologized for.\n- Then ask, clearly. The stack earns the right to a direct ask; don't waste it on \"let me know your thoughts.\"\n\n## Do this, not that\n\n**Do:** \"You're getting the full build, the brain set up from your real business, three workers configured to your jobs, and a call where I hand you the keys. Separately that's well into four figures of work. It's $997. Want me to send the booking link?\"\n\n**Don't:** Lead with \"It's $997\" cold, before they've been reminded what's in it — so the number is the first and biggest thing in their head and everything after sounds like justifying.\n\n## Why this works\n\nPrice feels expensive or cheap only relative to what it's next to. Name it before the value and it's a big number standing alone; name it after a stack of real things and it's a small number against a large total. Same price, opposite feeling. The stack does the persuading; the ask just collects the yes."
  },
  {
    "slug": "competitor-pricing-extract",
    "name": "Pull a Competitor's Pricing",
    "description": "Read a competitor's page and extract their real pricing — tiers, what's included, what's hidden — into a clean comparison.",
    "whenToUse": "Sizing up a competitor, setting the owner's own prices, or arming a sales conversation with what the other guy charges.",
    "tierRequired": "pro_plus",
    "category": "research",
    "prerequisites": [],
    "body": "# Pull a Competitor's Pricing\n\nA pricing page hides as much as it shows. Pull the actual tiers, what each includes, and the games — the \"contact us\" tier, the annual-only discount, the add-ons that aren't in the headline number.\n\n## The technique\n\n- Find every tier and its real monthly number — annualized if they only show the discounted yearly price.\n- List what each tier includes, and note where the page is vague on purpose.\n- Flag the hidden costs: setup fees, per-seat add-ons, overage charges, the \"call us\" enterprise tier that has no number.\n- Note the anchor — the tier they're steering you toward, usually the middle one made to look obvious.\n- Lay it out as a table the owner can read in ten seconds, and cite the page you pulled it from.\n\n## Do this, not that\n\n**Do:** \"Three tiers: $29, $79 (their anchor — 'most popular'), $199. The $29 caps at 100 contacts and has no integrations; the real entry price for a working setup is $79. Enterprise is 'contact us.' Annual billing knocks ~20%. Source: their /pricing, pulled today.\"\n\n**Don't:** Report \"they're cheaper than us\" off the headline $29 without noticing it's a stripped tier nobody actually uses, the real comparison is their $79 to your plan, and half their value is locked behind add-ons.\n\n## Why this works\n\nPricing pages are designed to look simple and hide the real cost. The headline number is bait; the working price is a tier or two up with add-ons attached. Pulling the actual structure — not the marketing number — is what lets the owner price against reality and lets sales say \"their real cost is X\" with a receipt instead of a guess."
  },
  {
    "slug": "customer-voice-extract",
    "name": "Pull Real Customer Quotes",
    "description": "Mine a transcript or review for the lines that sound like a real person, not a paraphrase — the exact words you can use in copy.",
    "whenToUse": "Building marketing copy, case studies, or messaging from a call recording, a review, or a testimonial. Anytime you need the customer's actual voice.",
    "tierRequired": "pro_plus",
    "category": "research",
    "prerequisites": [],
    "body": "# Pull Real Customer Quotes\n\nThe best copy is words a customer already said. Pull the verbatim lines that carry emotion and specificity, not your smoothed-over summary of them — the rough, real phrasing is what other customers recognize.\n\n## The technique\n\n- Pull verbatim. The exact phrase (\"I was drowning in paperwork\") beats your paraphrase (\"the client experienced administrative challenges\") every time.\n- Look for emotion and specificity — the lines where they got real, named a number, or described the moment it clicked.\n- Keep the rough edges. Real speech has them; polishing a quote into marketing-speak kills the thing that made it believable.\n- Tag each quote with what it proves — the pain, the result, the objection it overcomes — so you know where to use it.\n- Never invent or \"clean up\" a quote into something they didn't say. A fabricated testimonial is a liability, not an asset.\n\n## Do this, not that\n\n**Do:** Pull: \"Honestly I'd given up on finding someone who'd just show up when they said they would.\" — it's specific, emotional, and overcomes the no-show objection in the customer's own voice.\n\n**Don't:** Summarize it into \"The customer valued our reliability and professionalism\" — true, dead, and indistinguishable from every other company's testimonials.\n\n## Why this works\n\nProspects trust other customers' words far more than the company's. A verbatim quote with its rough edges intact reads as real — someone like them, talking like them. The moment you paraphrase it into clean marketing language, it sounds like you wrote it, and it stops doing the one job a testimonial has: proof from a peer."
  },
  {
    "slug": "tactic-extraction",
    "name": "Pull the Plays, Skip the Fluff",
    "description": "Read a long video or podcast transcript and extract the named, specific tactics worth keeping — not the stories and filler around them.",
    "whenToUse": "Processing a YouTube transcript, a podcast, or a long talk into something useful. When the owner wants the moves, not a book report.",
    "tierRequired": "pro_plus",
    "category": "research",
    "prerequisites": [],
    "body": "# Pull the Plays, Skip the Fluff\n\nMost of a talk is throat-clearing and stories. The value is the handful of specific, repeatable plays. Pull those — named, concrete, actionable — and drop the rest.\n\n## The technique\n\n- Hunt for the specific move: a number, a sequence, a rule, a script. \"Default to the highest package\" is a play; \"always provide value\" is filler.\n- Skip the stories unless the story IS the tactic. A war story that demonstrates a repeatable move is worth keeping; one that's just a flex isn't.\n- Keep it concrete enough to act on. If you can't picture doing it tomorrow, it's not a tactic, it's a vibe.\n- Name each play in a few words so it's findable later — that's how it becomes reusable instead of lost in a transcript.\n- Note who said it and where, so the owner can go back to the source if a play pays off.\n\n## Do this, not that\n\n**Do:** \"Play: on the order form, default-select the highest-margin package and let buyers downsize — most stay on the default, turning a 1-unit sale into 3. (Brunson, on order-form design.)\"\n\n**Don't:** Write \"He talked about the importance of optimizing your sales funnel and providing massive value to your audience\" — a summary of nothing the owner can actually do.\n\n## Why this works\n\nA 60-minute talk has maybe five minutes of plays you can run. The rest is rapport, repetition, and stories. Extracting the named, concrete tactics turns hours of content into a short list the owner can act on this week — and naming each one makes it a reusable move instead of a half-remembered idea that evaporates by Friday."
  },
  {
    "slug": "vertical-landscape-scan",
    "name": "One-Page Market Scan",
    "description": "Turn a handful of sources into a one-page read on a market or vertical — players, pricing, gaps, and where the opening is.",
    "whenToUse": "Entering a new vertical, sizing an opportunity, or briefing the owner before a decision about a market they don't know yet.",
    "tierRequired": "pro_plus",
    "category": "research",
    "prerequisites": [],
    "body": "# One-Page Market Scan\n\nA market scan is a one-page answer to \"what's the lay of the land and where's the opening?\" Pull from several sources, then compress to the players, the pricing reality, the gap, and the move.\n\n## The technique\n\n- Read several sources, not one — a single page gives you one company's spin, not the market.\n- Map the players in a line each: who they are, who they serve, what they charge. No essays.\n- Find the pricing reality across them — the real range, not any one headline number.\n- Name the gap: who's underserved, what nobody's doing well, where the complaints cluster.\n- End with the opening — the one move the gap suggests — and keep the whole thing to a page someone reads standing up.\n\n## Do this, not that\n\n**Do:** \"Roofing-measurement SaaS: three real players, $79–$299/mo, all aimed at big firms. Gap: nothing priced or simple enough for a 2–3 truck shop, and they all hide the supplement language solo operators actually need. Opening: a stripped, cheap tier for small contractors. Sources: 4 pricing pages + 2 forum threads, pulled today.\"\n\n**Don't:** Hand over ten pages of raw notes per competitor with no synthesis, no pricing comparison, and no answer to the only question that matters — where's the opening.\n\n## Why this works\n\nThe owner is making a decision, not writing a thesis. Ten pages of raw research pushes the synthesis work back onto them, which is the part they wanted done. A one-page scan that names the players, the pricing, the gap, and the move is something they can act on in a meeting — and pulling from several sources is what keeps it from being one competitor's marketing repeated back as fact."
  },
  {
    "slug": "source-verification",
    "name": "Every Claim Points at Its Source",
    "description": "Attach the URL or source to every factual claim in research, and flag anything you couldn't verify instead of stating it as fact.",
    "whenToUse": "Any research deliverable the owner will act on or repeat. Especially numbers, prices, and competitive claims that could be wrong.",
    "tierRequired": "pro_plus",
    "category": "research",
    "prerequisites": [],
    "body": "# Every Claim Points at Its Source\n\nA research claim without a source is a guess wearing a suit. Point every fact at where it came from, and when you can't verify something, say so plainly rather than laundering it into certainty.\n\n## The technique\n\n- Every number, price, and named fact gets its source inline — the URL, the page, the date pulled.\n- If you can't find the source, the claim doesn't ship as fact. Flag it: \"unverified — couldn't confirm.\"\n- Separate what you found from what you inferred. An inference is fine; passing it off as a sourced fact isn't.\n- Date the pull. Prices and pages change; a fact true last month may be stale, and the date tells the reader how much to trust it.\n- When two sources disagree, say so and show both — don't silently pick one and present it as settled.\n\n## Do this, not that\n\n**Do:** \"Their entry price is $79/mo (their /pricing page, pulled 2026-06-09). Their churn is reportedly high — unverified, that's from one forum thread, treat as a rumor, not a number.\"\n\n**Don't:** State \"they charge $79 and have terrible retention\" as flat fact, where the price is sourced but the retention is a stranger's comment you can't back up — now the owner repeats a rumor as data.\n\n## Why this works\n\nResearch gets repeated. The owner will say it on a call, put it in a deck, price against it. If a claim is wrong and there's no source, nobody catches it until it's already cost something. Sourcing every fact makes the work checkable and the mistakes findable, and flagging the unverified keeps a guess from hardening into a \"fact\" that wasn't."
  },
  {
    "slug": "inbox-triage",
    "name": "Triage the Inbox",
    "description": "Sort a full inbox into respond-now, respond-this-week, archive, and delegate — so the owner sees the few things that actually need them.",
    "whenToUse": "A backed-up inbox, a morning review, or a daily brief. Anytime the volume is hiding the few messages that matter.",
    "tierRequired": "studio_plus",
    "category": "operations",
    "prerequisites": [],
    "body": "# Triage the Inbox\n\nMost of an inbox is noise. Triage it into four piles — now, this week, archive, delegate — so the owner spends their attention on the handful that's actually time-sensitive and theirs to handle.\n\n## The technique\n\n- Respond-now: money on the line, an angry customer, a deadline today, a deal that moves if you move. These surface first.\n- Respond-this-week: real but not urgent. Batch them so they don't interrupt the now-pile.\n- Archive: newsletters, receipts, FYIs, threads that resolved themselves. Out of the way, not deleted.\n- Delegate: things someone else (or the agent) can handle — draft the reply, route it, flag it for a person.\n- Surface the now-pile as a short list with one line each, so the owner sees what needs them at a glance.\n\n## Do this, not that\n\n**Do:** \"3 need you now: the Henderson invoice dispute, a hot lead asking to book, and the supplier's deadline today. 6 can wait till Thursday. Archived 40 receipts and newsletters. I can draft replies to the 6 — want me to?\"\n\n**Don't:** Hand back \"You have 49 unread emails\" with no sort — which is the same as handing back the problem, since now the owner has to triage all 49 themselves.\n\n## Why this works\n\nAn inbox punishes the owner for every minute they're away by burying the three messages that matter under forty that don't. Triage flips that — it does the sorting so the owner spends attention only where it counts. The four-pile split works because it maps to the only decision that matters per message: does this need me, now, ever, or not at all."
  },
  {
    "slug": "project-scaffolding",
    "name": "Break a Goal Into Steps",
    "description": "Turn a vague goal into milestones, then milestones into concrete tasks, so a big ask becomes a sequence someone can actually run.",
    "whenToUse": "The owner names a goal that's too big to act on directly — \"launch the new service,\" \"clean up the books.\" Use before any of it gets dispatched as work.",
    "tierRequired": "studio_plus",
    "category": "operations",
    "prerequisites": [],
    "body": "# Break a Goal Into Steps\n\nA goal you can't start is a goal stated too big. Break it into a few milestones — the real phases — then break each milestone into tasks small enough to do. The scaffold is what makes it run.\n\n## The technique\n\n- Restate the goal as a finished outcome, so \"done\" is unambiguous before you plan a single step.\n- Split into milestones — 3 to 5 real phases, each a chunk that ends in something you can point at.\n- Under each milestone, list tasks small enough to actually do — a task is one clear action, not another mini-project.\n- Order them by dependency: what has to finish before the next thing can start. Surface what can run in parallel.\n- Name the first task precisely. A plan that doesn't make the next move obvious is a plan nobody starts.\n\n## Do this, not that\n\n**Do:** \"Goal: launch the maintenance plan. Milestone 1: define the offer (price it, write what's included, set the terms). Milestone 2: build it (Stripe product, sign-up page, contract). Milestone 3: sell it (email the 40 past customers, add it to quotes). First task: write the three-tier price list — start there.\"\n\n**Don't:** Take \"launch the maintenance plan\" and either freeze because it's too big, or jump straight to building a sign-up page before the offer or price even exists.\n\n## Why this works\n\nBig goals stall because there's no obvious first move — the whole thing has to be held in your head at once. Scaffolding externalizes the structure: milestones make the size manageable, tasks make each piece doable, and ordering by dependency stops you from building the sign-up page before you've decided what you're selling. The named first task is what turns a plan into momentum."
  },
  {
    "slug": "quote-drafting-from-notes",
    "name": "Draft a Quote From Messy Notes",
    "description": "Turn rough notes — a photo, a voice memo, a few scribbled lines — into a clean, structured quote with scope, line items, and a total.",
    "whenToUse": "The owner captured a job in the field — a quick note, a photo, a memo — and needs it turned into a quote they can send.",
    "tierRequired": "studio_plus",
    "category": "operations",
    "prerequisites": [],
    "body": "# Draft a Quote From Messy Notes\n\nField notes are messy on purpose; the owner was busy. Turn them into a real quote: the scope in plain terms, line items with quantities and prices, a total, and the terms — structured so it's ready to send.\n\n## The technique\n\n- Pull the job out of the mess — what's being done, where, what condition things are in. Reconstruct the scope from the notes and photos.\n- Break it into line items: each piece of work with a quantity and a price the owner can stand behind.\n- Use the owner's real pricing from the brain, not made-up numbers. If a price is missing, flag it — don't invent it.\n- Add the terms: what's included, what's not, how long the quote holds, payment schedule.\n- Total it, write a one-line cover in the owner's voice, and stage it for the owner to check before it goes out.\n\n## Do this, not that\n\n**Do:** From \"roof, 20sq, some rot on the north side, customer wants gutters too\" → a quote with tear-off (20 sq), decking replacement (north section, flagged: confirm sq footage), new gutters (linear ft), each priced from the owner's list, totaled, with a 'valid 30 days' line.\n\n**Don't:** Either hand back the raw notes reformatted with no prices, or invent prices the owner never set — both leave the owner doing the actual quoting or, worse, sending a number they can't honor.\n\n## Why this works\n\nThe gap between a captured job and a sent quote is where deals go cold — the owner means to write it up tonight and it's still sitting there Friday. Turning the notes into a ready-to-send quote closes that gap. Pulling real prices from the brain (and flagging the ones you don't have) is what keeps it honest: a fast quote that quotes the wrong number is worse than a slow one."
  },
  {
    "slug": "vendor-invoice-categorization",
    "name": "Categorize a Vendor Invoice",
    "description": "Read a vendor invoice and log it to the right account so the books stay clean and tax time isn't a scramble.",
    "whenToUse": "A vendor bill or receipt comes in and needs to land in the books under the correct category.",
    "tierRequired": "studio_plus",
    "category": "operations",
    "prerequisites": [],
    "body": "# Categorize a Vendor Invoice\n\nEvery invoice has a right home in the books. Read what it's actually for, match it to the correct account, and log it with enough detail that it makes sense at tax time without a second look.\n\n## The technique\n\n- Read what the invoice is for, not just who it's from — a hardware-store receipt could be materials, tools, or an office supply, and the category depends on the line items.\n- Match it to the right account in the owner's chart of accounts. Use the categories that already exist; don't invent a new one for a one-off.\n- Split it when it's mixed — if one receipt covers materials and equipment, split the lines rather than dumping it all in one bucket.\n- Note the job or customer when it's billable, so it can be tied back to revenue later.\n- When the category is actually unclear, flag it for the owner instead of guessing — a wrong category quietly compounds into a tax-time mess.\n\n## Do this, not that\n\n**Do:** \"Supplier invoice $1,240: $1,100 shingles → Materials (job: Henderson, billable); $140 nail gun → Tools & Equipment. Split logged. The $90 'misc' line is unclear — flagged for you.\"\n\n**Don't:** Dump the whole $1,240 into \"Supplies\" because it came from a supplier — mixing a capital tool purchase with billable job materials, which throws off both job costing and the deduction.\n\n## Why this works\n\nMiscategorized invoices don't hurt today — they hurt in April, when the books don't reconcile and the deductions are wrong. Logging each one to the right account as it comes in keeps the books clean continuously, ties costs back to the jobs that earned the revenue, and means tax time is a review instead of a forensic reconstruction. Flagging the unclear ones beats a confident wrong guess that nobody catches for months."
  },
  {
    "slug": "end-of-day-reflection",
    "name": "End-of-Day Reflection",
    "description": "Pull the day's real activity — what shipped, what moved, what's stuck — and hand the owner a short read on what changed.",
    "whenToUse": "End of the workday, as a routine or on demand. When the owner wants to close the day knowing what actually happened.",
    "tierRequired": "studio_plus",
    "category": "operations",
    "prerequisites": [],
    "body": "# End-of-Day Reflection\n\nAt day's end the owner should know what changed without reconstructing it from memory. Pull the real activity — what got done, what moved forward, what's stuck — and hand back a short, honest read.\n\n## The technique\n\n- Pull what actually happened from the day's real activity — sent emails, closed tasks, calls, approvals — not a vibe.\n- Lead with what shipped: the things that are done and verified, named specifically.\n- Name what moved but isn't finished, and what's stuck and why — the blockers are the part the owner needs most.\n- Surface anything that needs the owner tomorrow — a decision waiting, a follow-up due, a deadline approaching.\n- Keep it short. A reflection that takes ten minutes to read defeats the point; the owner wants the day in thirty seconds.\n\n## Do this, not that\n\n**Do:** \"Today: sent 3 quotes (Henderson, Diaz, the gutter job), closed the Miller invoice, booked Thursday's crew. Stuck: the supplier still hasn't confirmed the material price — that's blocking the Diaz start. Tomorrow needs you: call Dave back, and the Miller follow-up is due.\"\n\n**Don't:** Hand back \"It was a productive day with good progress across several areas!\" — a feeling, not a read, that tells the owner nothing and surfaces no blocker.\n\n## Why this works\n\nOwners carry the whole business in their head, and at the end of a busy day that head is full and unreliable. A reflection built from real activity — not memory, not vibes — lets them close the day knowing what actually changed and start tomorrow knowing what needs them. The blockers matter most: those are the things that quietly stall the business while everyone assumes they're handled."
  },
  {
    "slug": "three-option-framing",
    "name": "Always Three Options",
    "description": "Frame a decision as three real options with their trade-offs, never a single take-it-or-leave-it recommendation.",
    "whenToUse": "Any time the owner faces a real choice — a vendor, a price, a direction. When you'd otherwise just hand them one answer.",
    "tierRequired": "studio_plus",
    "category": "decision_shape",
    "prerequisites": [],
    "body": "# Always Three Options\n\nOne option is an order; three options is a decision. Give the owner three real paths with honest trade-offs so they're choosing, not just approving the one thing you put in front of them.\n\n## The technique\n\n- Build three genuine options, not one real choice padded with two strawmen. Each has to be something a reasonable person might pick.\n- Name the trade-off on each — what you give up to get what it offers. No option is free; show the cost.\n- Make them actually different: a cheap-and-fast, a safe-and-thorough, a bold-and-risky — not three shades of the same move.\n- Say which you'd pick and why, but after laying out all three — a recommendation, not a foregone conclusion.\n- Keep it scannable: three options, the trade-off on each, your pick last. The owner decides in a minute.\n\n## Do this, not that\n\n**Do:** \"Three ways to go on the hire: (A) contractor now — fast, flexible, costs more per hour. (B) part-timer — cheaper, slower to ramp, you manage them. (C) wait a quarter — no cost, but you stay the bottleneck. I'd do A — the bottleneck's costing more than the rate. Your call.\"\n\n**Don't:** Hand back \"You should hire a contractor\" with no alternatives — so the owner either rubber-stamps it or has to go generate the options themselves to feel like they actually decided.\n\n## Why this works\n\nA single recommendation puts the owner in a corner: agree or push back, with no map of the territory. Three real options with trade-offs hands them the map — they see what each path costs and choose with their eyes open. It also surfaces the option you might have missed, and it respects that it's their business and their call, not yours to make by omission."
  },
  {
    "slug": "load-bearing-assumption",
    "name": "Name the Load-Bearing Assumption",
    "description": "Find the one assumption that makes a decision wrong if it's false, and check it before committing.",
    "whenToUse": "Before a real commitment — a hire, a spend, a direction. When a plan depends on something being true that nobody's actually checked.",
    "tierRequired": "studio_plus",
    "category": "decision_shape",
    "prerequisites": [],
    "body": "# Name the Load-Bearing Assumption\n\nEvery plan rests on one or two assumptions that, if wrong, sink it. Find the load-bearing one — the thing that has to be true for this to work — and pressure-test it before you commit, not after.\n\n## The technique\n\n- Ask what has to be true for this decision to be right. List the assumptions underneath it.\n- Find the load-bearing one — the assumption that, if false, makes the whole thing a mistake. There's usually one that matters most.\n- Check whether you actually know it's true, or just hope it is. Hope is not a check.\n- If it's unverified, verify it before committing — a cheap test now beats an expensive correction later.\n- If you can't verify it, size the downside: what does being wrong cost? That tells you how much to bet.\n\n## Do this, not that\n\n**Do:** \"This whole plan assumes the 40 past customers actually want a maintenance plan — that's load-bearing. Before we build it, I'll email ten of them and ask. If half say yes, build it. If nobody bites, we just saved the build.\"\n\n**Don't:** Build the entire maintenance-plan system, the page, the Stripe product, the contracts — on the unchecked assumption that demand exists, then discover after launch that nobody wanted it.\n\n## Why this works\n\nPlans don't usually fail on the details; they fail on a wrong assumption nobody questioned. Naming the load-bearing one turns an invisible bet into a visible one you can actually test. Most of the time the test is cheap — an email, a few calls — and finding out the assumption is false before you build is the difference between a saved week and a wasted month."
  },
  {
    "slug": "devils-advocate-first-pass",
    "name": "Argue the Other Side First",
    "description": "Before agreeing with a plan, find its strongest counter-argument and state it — so the owner decides against a real objection, not a yes-man.",
    "whenToUse": "When the owner proposes something and you're inclined to agree. Especially on big or expensive calls where easy agreement is dangerous.",
    "tierRequired": "studio_plus",
    "category": "decision_shape",
    "prerequisites": [],
    "body": "# Argue the Other Side First\n\nThe most useful thing an agent can do with a plan it likes is attack it first. Find the strongest case against it — not a token objection — and put it on the table before you sign off.\n\n## The technique\n\n- Before agreeing, ask: what's the best argument against this? Build the case a smart skeptic would make.\n- Make it the strongest version, not a strawman you can easily knock down. If the counter is weak, you haven't found the real one.\n- Name the specific failure: how this goes wrong, who it hurts, what it costs — concretely, not \"there are risks.\"\n- Then weigh it straight. Sometimes the counter wins and the plan should change; sometimes it loses and you proceed with eyes open.\n- Surface the counter even when you ultimately agree — the owner deserves to decide against a real objection, not a chorus.\n\n## Do this, not that\n\n**Do:** \"I think the maintenance plan's a good move, but here's the strongest case against it: it ties up your crew on low-margin recurring work right when storm season pays triple. If your crew's already maxed, this could cost you the high-margin jobs. Worth checking your capacity before we commit.\"\n\n**Don't:** Reply \"Great idea, let's do it!\" because the owner sounded confident — adding nothing, catching nothing, and leaving the real risk for them to discover the hard way.\n\n## Why this works\n\nAn agent that always agrees is worthless on the decisions that matter — it just echoes the owner's confidence back at them, including the overconfidence. Arguing the other side first is how you earn your seat: you catch the failure mode the owner was too close to see. Even when the plan survives, it survives a real test, which is exactly the kind of pressure a good decision should pass."
  },
  {
    "slug": "reversibility-check",
    "name": "Check Whether It's Reversible",
    "description": "Decide how much to deliberate by whether the decision can be undone — move fast on reversible calls, slow down on the one-way doors.",
    "whenToUse": "Any decision where you're unsure how much time it deserves. The check tells you whether to just decide or to slow down.",
    "tierRequired": "studio_plus",
    "category": "decision_shape",
    "prerequisites": [],
    "body": "# Check Whether It's Reversible\n\nNot every decision deserves the same care. Ask whether you can undo it cheaply. If yes, decide fast and move. If no — a one-way door — slow down, because the cost of being wrong is permanent.\n\n## The technique\n\n- Ask: if this is wrong, how hard is it to reverse? Cheap-to-undo and costly-to-undo are different decisions.\n- Reversible calls: decide fast, with less information. Over-deliberating a thing you can take back is its own kind of waste.\n- One-way doors — a fire, a contract you can't exit, money you can't get back, a public move: slow down and gather more before committing.\n- Don't treat every decision as permanent. Most aren't, and acting like they are grinds the business to a halt.\n- Don't treat a permanent one as casual either. The whole skill is matching the deliberation to the reversibility.\n\n## Do this, not that\n\n**Do:** \"Switching email tools? Reversible — try it, switch back if it's worse, decide in an afternoon. Signing the two-year lease on the second location? One-way door — that one gets the slow, careful look.\"\n\n**Don't:** Spend two weeks agonizing over which $20 software to use (reversible, just pick one) while signing a major lease on a gut feeling because it felt exciting in the moment (irreversible, deserved the agonizing).\n\n## Why this works\n\nPeople burn their deliberation budget backwards — they over-think the small reversible stuff and under-think the big permanent stuff, because urgency and stakes don't line up with reversibility. Sorting by whether a decision can be undone fixes that: fast on the two-way doors, slow on the one-way doors. It's the single best filter for how much a decision is worth worrying about."
  },
  {
    "slug": "pre-mortem",
    "name": "Run a Pre-Mortem",
    "description": "Before committing, assume the plan already failed and write down why — so you fix the likely failures before they happen.",
    "whenToUse": "Before launching something real — a service, a campaign, a big spend. When the plan feels solid and that confidence needs a stress test.",
    "tierRequired": "studio_plus",
    "category": "decision_shape",
    "prerequisites": [],
    "body": "# Run a Pre-Mortem\n\nA pre-mortem is a post-mortem you run before the failure. Assume the plan has already failed, six months out, then write the story of how — and use that story to fix the weak points now.\n\n## The technique\n\n- Imagine it's six months later and this clearly failed. Don't ask if — assume it did.\n- Write the story of how it failed. The specific causes, not \"it didn't work\": the demand wasn't there, the crew burned out, the price was wrong, a competitor moved first.\n- Rank the failure modes by likelihood and damage — which of these stories is most plausible and most costly.\n- Fix the top one or two now, while it's cheap. A pre-mortem that doesn't change the plan was just theater.\n- Keep the list. When something starts going sideways later, you've already named it and can act fast.\n\n## Do this, not that\n\n**Do:** \"Pre-mortem on the maintenance plan: it failed because (1) only 5 of 40 customers signed up — demand was thin; (2) the recurring work ate crew time we needed for storm jobs; (3) churn after month two because the value wasn't visible. Fix now: test demand with 10 calls first, cap enrollment to protect crew capacity, build in a monthly 'here's what we did' touch.\"\n\n**Don't:** Launch on pure optimism — \"this is going to be great\" — and run the actual post-mortem in six months after the avoidable failures have already cost real money.\n\n## Why this works\n\nConfidence makes you blind to a plan's weak points right when you most need to see them. A pre-mortem gets around that by giving everyone permission to imagine failure — it's easier to spot what could go wrong when you start from \"it did\" instead of defending \"it will work.\" The failures you name in advance are the ones you can still prevent cheaply; the ones you don't name, you pay for later at full price."
  }
];
