import type { CaptureSurfaceKey } from "@/data/pocket-capture/marketing";

// One capture-surface demo video per surface (PC-MARK-6). Files live under
// public/pocket-capture/demos/ and are generated by scripts/pocket-capture/generate-demo-videos.mjs
// (deterministic Playwright mockup + Chase's cloned ElevenLabs voiceover + ffmpeg). They sit
// below the fold in How It Works, so autoplay-muted-loop is safe for LCP. Inline playback is
// silent by design — the voiceover track rides along for paid-social ad reuse (PC-ADS-2).
// The `data-demo-surface` attribute stays as the stable wiring point.

const DEMO_SRC: Record<CaptureSurfaceKey, string> = {
  share: "/pocket-capture/demos/share-sheet.mp4",
  voice: "/pocket-capture/demos/voice-shortcut.mp4",
  email: "/pocket-capture/demos/email-forward.mp4",
  sms: "/pocket-capture/demos/sms.mp4",
};

export function DemoSlot({
  surfaceKey,
  label,
  icon,
  className = "",
}: {
  surfaceKey: CaptureSurfaceKey;
  label: string;
  icon: string;
  className?: string;
}) {
  const src = DEMO_SRC[surfaceKey];

  return (
    <div
      data-demo-surface={surfaceKey}
      className={`relative aspect-[9/16] overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03] ${className}`}
      aria-label={`${label} demo`}
    >
      <video
        className="h-full w-full object-cover"
        src={src}
        autoPlay
        muted
        loop
        playsInline
        preload="metadata"
        aria-hidden
      >
        {/* Fallback for browsers that won't render the video element. */}
        <span className="flex h-full w-full flex-col items-center justify-center gap-2 text-slate-300">
          <span className="text-3xl" aria-hidden>
            {icon}
          </span>
          <span className="text-xs font-medium">{label}</span>
        </span>
      </video>
    </div>
  );
}
