// directions-meta.ts — GENERATED by scripts/gen-landing-page-directions.mjs. Do not edit by hand.
// The catalog counts for surfaces that show the number without needing the catalog itself.
// Note: 8 extra studio_plus animated-React directions added 2026-06-14 (not from the gen script).

export const DIRECTION_COUNTS = {
  total: 150,
  starter: 58,
  studioPlus: 92,
} as const;
