// directions-meta.ts — GENERATED by scripts/gen-landing-page-directions.mjs. Do not edit by hand.
// The catalog counts for surfaces that show the number without needing the catalog itself.

export const DIRECTION_COUNTS = {
  total: 142,
  starter: 58,
  studioPlus: 84,
} as const;
