// personal-brand.ts — the template for a coach or consultant: hero + bio + offerings list +
// lead-magnet capture + a call to action. Same {{COPY_JSON}} contract: each section's copy is one
// string (first line = headline, "- " lines become points).

import type { LandingTemplate } from "@/lib/landing-pages/types";

const COMPONENT_TEMPLATE = `// app/page.tsx — generated by Pocket Agent, Landing Page Builder. This is your code; edit it freely.
type Copy = Record<string, string>;

const copy: Copy = {{COPY_JSON}};

function lines(text: string): string[] {
  return (text || "").split("\\n").map((l) => l.trim()).filter(Boolean);
}

function bullets(text: string): string[] {
  return lines(text).slice(1).filter((l) => l.startsWith("- ")).map((l) => l.slice(2));
}

function Heading({ text }: { text: string }) {
  return <h2 style={{ fontSize: 28, fontWeight: 800, margin: "0 0 14px", color: "#0f172a", letterSpacing: "-0.02em" }}>{text}</h2>;
}

export default function Page() {
  const heroLines = lines(copy.hero);
  const headline = heroLines[0] || "Work with me";
  const subhead = heroLines.slice(1).join(" ");
  return (
    <main style={{ fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, sans-serif", color: "#0f172a", margin: 0 }}>
      <section style={{ background: "linear-gradient(180deg,#0f766e,#115e59)", color: "#f0fdfa", padding: "96px 24px", textAlign: "center" }}>
        <div style={{ maxWidth: 760, margin: "0 auto" }}>
          <h1 style={{ fontSize: 46, fontWeight: 900, margin: "0 0 18px", letterSpacing: "-0.03em", lineHeight: 1.08 }}>{headline}</h1>
          <p style={{ fontSize: 20, color: "#99f6e4", lineHeight: 1.6, margin: "0 0 32px" }}>{subhead}</p>
          <a href="#capture" style={{ display: "inline-block", background: "#5eead4", color: "#134e4a", fontWeight: 800, fontSize: 17, padding: "16px 32px", borderRadius: 12, textDecoration: "none" }}>Get the free guide</a>
        </div>
      </section>
      <section style={{ maxWidth: 720, margin: "0 auto", padding: "72px 24px" }}>
        <Heading text={lines(copy.bio)[0] || "About"} />
        {lines(copy.bio).slice(1).map((line, i) => (
          <p key={i} style={{ margin: "10px 0", color: "#334155", lineHeight: 1.7, fontSize: 17 }}>{line.replace(/^- /, "\\u2022 ")}</p>
        ))}
      </section>
      <section style={{ background: "#f0fdfa", padding: "72px 24px" }}>
        <div style={{ maxWidth: 820, margin: "0 auto" }}>
          <Heading text={lines(copy.offerings)[0] || "How I can help"} />
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 18, marginTop: 20 }}>
            {bullets(copy.offerings).map((item, i) => (
              <div key={i} style={{ background: "#fff", borderRadius: 14, padding: 22, boxShadow: "0 1px 3px rgba(19,78,74,0.1)", color: "#334155", lineHeight: 1.6, fontSize: 16 }}>{item}</div>
            ))}
          </div>
        </div>
      </section>
      <section id="capture" style={{ maxWidth: 620, margin: "0 auto", padding: "76px 24px", textAlign: "center" }}>
        <Heading text={lines(copy.lead_magnet)[0] || "Get the free guide"} />
        {lines(copy.lead_magnet).slice(1).map((line, i) => (
          <p key={i} style={{ margin: "8px 0", color: "#334155", lineHeight: 1.7, fontSize: 17 }}>{line.replace(/^- /, "\\u2022 ")}</p>
        ))}
        <form style={{ display: "flex", gap: 10, marginTop: 18, flexWrap: "wrap", justifyContent: "center" }}>
          <input type="email" placeholder="you@email.com" style={{ flex: "1 1 220px", padding: "14px 16px", borderRadius: 12, border: "1px solid #cbd5e1", fontSize: 16 }} />
          <button type="submit" style={{ background: "#0f766e", color: "#f0fdfa", fontWeight: 800, fontSize: 16, padding: "14px 26px", borderRadius: 12, border: "none", cursor: "pointer" }}>Send it to me</button>
        </form>
      </section>
      <section style={{ background: "#134e4a", color: "#f0fdfa", padding: "72px 24px", textAlign: "center" }}>
        <div style={{ maxWidth: 640, margin: "0 auto" }}>
          <h2 style={{ fontSize: 28, fontWeight: 800, margin: "0 0 14px" }}>{lines(copy.cta)[0] || "Ready to work together?"}</h2>
          {lines(copy.cta).slice(1).map((line, i) => (
            <p key={i} style={{ margin: "8px 0", color: "#99f6e4", lineHeight: 1.7, fontSize: 17 }}>{line.replace(/^- /, "\\u2022 ")}</p>
          ))}
          <a href="mailto:" style={{ display: "inline-block", marginTop: 18, background: "#5eead4", color: "#134e4a", fontWeight: 800, fontSize: 17, padding: "16px 32px", borderRadius: 12, textDecoration: "none" }}>Book a call</a>
        </div>
      </section>
    </main>
  );
}
`;

export const personalBrandTemplate: LandingTemplate = {
  id: "personal-brand",
  label: "Personal brand",
  description: "Hero, your story, what you offer, a free-guide capture, and a call to action.",
  bestFor: "A coach or consultant whose name and story are the draw.",
  sections: [
    { key: "hero", kind: "hero", label: "Hero", purpose: "The promise to the visitor and who you help, in a headline and subhead." },
    { key: "bio", kind: "bio", label: "Your story", purpose: "A short, credible bio in the owner's voice — why they can help." },
    { key: "offerings", kind: "offerings", label: "What you offer", purpose: "The ways the owner helps, as a short list of offerings." },
    { key: "lead_magnet", kind: "lead_magnet", label: "Free guide", purpose: "The free thing the visitor gets for their email, and why it's worth it." },
    { key: "cta", kind: "cta", label: "Call to action", purpose: "A warm close that invites the visitor to take the next step." },
  ],
  defaultCopyPrompts: {
    hero:
      "Write the hero for a personal brand. Line 1 is the headline — the promise to the visitor and who you help, " +
      "under 10 words. The lines after are a one-sentence subhead in the owner's voice.",
    bio:
      "Write a short bio. Line 1 is a short headline. The body is 2-3 lines in the owner's voice — who they are, who " +
      "they help, and why they're credible. Real, not a resume. Never invent credentials.",
    offerings:
      "Write the offerings. Line 1 is a short headline. Then 2-4 lines, each starting with '- ', one per way the owner " +
      "helps (a program, a service, a session). One line each, concrete.",
    lead_magnet:
      "Write the lead-magnet capture. Line 1 is a short headline naming the free thing. The body is one or two lines " +
      "on what's inside and why it's worth an email. Specific, no hype.",
    cta:
      "Write the closing call to action. Line 1 is a short, warm headline inviting the next step. The body is one or " +
      "two lines that lower the friction. Inviting, not pushy.",
  },
  componentTemplate: COMPONENT_TEMPLATE,
};
