// single-cta.ts — the default template for a service business: hero + problem + 3-step mechanism +
// one clear call to action. The component skeleton carries a single {{COPY_JSON}} placeholder the
// assembler fills with the generated copy (as data, never spliced into JSX). Each section's copy is
// one string: first line is the section headline, the rest is the body ("- " lines become points).

import type { LandingTemplate } from "@/lib/landing-pages/types";

const COMPONENT_TEMPLATE = `// app/page.tsx — generated by Pocket Agent, Landing Page Builder. This is your code; edit it freely.
type Copy = Record<string, string>;

const copy: Copy = {{COPY_JSON}};

function lines(text: string): string[] {
  return (text || "").split("\\n").map((l) => l.trim()).filter(Boolean);
}

function Heading({ text }: { text: string }) {
  return <h2 style={{ fontSize: 30, fontWeight: 800, margin: "0 0 14px", color: "#0f172a", letterSpacing: "-0.02em" }}>{text}</h2>;
}

function Body({ text }: { text: string }) {
  return (
    <>
      {lines(text).map((line, i) => (
        <p key={i} style={{ margin: "10px 0", color: "#334155", lineHeight: 1.7, fontSize: 17 }}>
          {line.replace(/^- /, "\\u2022 ")}
        </p>
      ))}
    </>
  );
}

export default function Page() {
  const heroLines = lines(copy.hero);
  const headline = heroLines[0] || "Your offer, made clear";
  const subhead = heroLines.slice(1).join(" ");
  const mech = lines(copy.mechanism);
  const mechHead = mech[0] || "How it works";
  const steps = mech.slice(1).filter((l) => l.startsWith("- ")).map((l) => l.slice(2));
  return (
    <main style={{ fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, sans-serif", color: "#0f172a", margin: 0 }}>
      <section style={{ background: "linear-gradient(180deg,#0b1220,#111c2e)", color: "#f8fafc", padding: "96px 24px", textAlign: "center" }}>
        <div style={{ maxWidth: 760, margin: "0 auto" }}>
          <h1 style={{ fontSize: 48, fontWeight: 900, margin: "0 0 18px", letterSpacing: "-0.03em", lineHeight: 1.05 }}>{headline}</h1>
          <p style={{ fontSize: 20, color: "#cbd5e1", lineHeight: 1.6, margin: "0 0 32px" }}>{subhead}</p>
          <a href="#start" style={{ display: "inline-block", background: "#22d3ee", color: "#06121a", fontWeight: 800, fontSize: 17, padding: "16px 32px", borderRadius: 12, textDecoration: "none" }}>Get a free quote</a>
        </div>
      </section>
      <section style={{ maxWidth: 760, margin: "0 auto", padding: "72px 24px" }}>
        <Heading text={lines(copy.problem)[0] || "The problem"} />
        <Body text={lines(copy.problem).slice(1).join("\\n")} />
      </section>
      <section style={{ background: "#f1f5f9", padding: "72px 24px" }}>
        <div style={{ maxWidth: 900, margin: "0 auto" }}>
          <Heading text={mechHead} />
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 20, marginTop: 24 }}>
            {steps.map((step, i) => (
              <div key={i} style={{ background: "#fff", borderRadius: 14, padding: 24, boxShadow: "0 1px 3px rgba(15,23,42,0.08)" }}>
                <div style={{ width: 34, height: 34, borderRadius: 999, background: "#0b1220", color: "#22d3ee", display: "grid", placeItems: "center", fontWeight: 800, marginBottom: 12 }}>{i + 1}</div>
                <p style={{ margin: 0, color: "#334155", lineHeight: 1.6, fontSize: 16 }}>{step}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      <section id="start" style={{ maxWidth: 680, margin: "0 auto", padding: "84px 24px", textAlign: "center" }}>
        <Heading text={lines(copy.cta)[0] || "Ready to start?"} />
        <Body text={lines(copy.cta).slice(1).join("\\n")} />
        <a href="mailto:" style={{ display: "inline-block", marginTop: 18, background: "#0b1220", color: "#f8fafc", fontWeight: 800, fontSize: 17, padding: "16px 32px", borderRadius: 12, textDecoration: "none" }}>Get a free quote</a>
      </section>
    </main>
  );
}
`;

export const singleCtaTemplate: LandingTemplate = {
  id: "single-cta",
  label: "Single call-to-action",
  description: "Hero, the problem you solve, a three-step explanation, and one clear ask.",
  bestFor: "A service business that wants one page that turns a visitor into a lead.",
  sections: [
    { key: "hero", kind: "hero", label: "Hero", purpose: "The headline promise and a one-line subhead that names the offer." },
    { key: "problem", kind: "problem", label: "The problem", purpose: "The pain the visitor feels right now, named plainly so they feel understood." },
    { key: "mechanism", kind: "mechanism", label: "How it works", purpose: "Three simple steps that show how the work gets done." },
    { key: "cta", kind: "cta", label: "Call to action", purpose: "A short, confident close that asks for the one next step." },
  ],
  defaultCopyPrompts: {
    hero:
      "Write the hero. Line 1 is the headline — a specific promise the business can keep, no hype, under 10 words. " +
      "Lines after it are a one-sentence subhead that names what's offered and who it's for.",
    problem:
      "Write the problem section. Line 1 is a short headline. The body names the pain the visitor feels today — " +
      "concrete, in their words, no fear-mongering. 2-3 short lines.",
    mechanism:
      "Write the 'how it works' section. Line 1 is a short headline. Then exactly three lines, each starting with " +
      "'- ', one per step — plain, active, what the business actually does. No jargon.",
    cta:
      "Write the closing call to action. Line 1 is a short headline that asks for the next step. The body is one or " +
      "two lines that make it easy to say yes. Confident, not pushy.",
  },
  componentTemplate: COMPONENT_TEMPLATE,
};
