// vertical-pack.ts — the template for a productized service: hero + niche-specific problem +
// before/after + tier comparison + a bundled call to action. Same {{COPY_JSON}} contract as the other
// templates: each section's copy is one string (first line = headline, "- " lines become points).

import type { LandingTemplate } from "@/lib/landing-pages/types";

const COMPONENT_TEMPLATE = `// app/page.tsx — generated by Pocket Agent, Landing Page Builder. This is your code; edit it freely.
type Copy = Record<string, string>;

const copy: Copy = {{COPY_JSON}};

function lines(text: string): string[] {
  return (text || "").split("\\n").map((l) => l.trim()).filter(Boolean);
}

function bullets(text: string): string[] {
  return lines(text).slice(1).filter((l) => l.startsWith("- ")).map((l) => l.slice(2));
}

function Heading({ text }: { text: string }) {
  return <h2 style={{ fontSize: 30, fontWeight: 800, margin: "0 0 14px", color: "#0f172a", letterSpacing: "-0.02em" }}>{text}</h2>;
}

export default function Page() {
  const heroLines = lines(copy.hero);
  const headline = heroLines[0] || "A done-for-you package";
  const subhead = heroLines.slice(1).join(" ");
  return (
    <main style={{ fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, sans-serif", color: "#0f172a", margin: 0 }}>
      <section style={{ background: "linear-gradient(180deg,#1e1b4b,#312e81)", color: "#f8fafc", padding: "96px 24px", textAlign: "center" }}>
        <div style={{ maxWidth: 780, margin: "0 auto" }}>
          <h1 style={{ fontSize: 48, fontWeight: 900, margin: "0 0 18px", letterSpacing: "-0.03em", lineHeight: 1.05 }}>{headline}</h1>
          <p style={{ fontSize: 20, color: "#c7d2fe", lineHeight: 1.6, margin: "0 0 32px" }}>{subhead}</p>
          <a href="#start" style={{ display: "inline-block", background: "#a78bfa", color: "#1e1b4b", fontWeight: 800, fontSize: 17, padding: "16px 32px", borderRadius: 12, textDecoration: "none" }}>See the packages</a>
        </div>
      </section>
      <section style={{ maxWidth: 760, margin: "0 auto", padding: "72px 24px" }}>
        <Heading text={lines(copy.problem)[0] || "The problem"} />
        {lines(copy.problem).slice(1).map((line, i) => (
          <p key={i} style={{ margin: "10px 0", color: "#334155", lineHeight: 1.7, fontSize: 17 }}>{line.replace(/^- /, "\\u2022 ")}</p>
        ))}
      </section>
      <section style={{ background: "#f5f3ff", padding: "72px 24px" }}>
        <div style={{ maxWidth: 860, margin: "0 auto" }}>
          <Heading text={lines(copy.before_after)[0] || "Before and after"} />
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: 18, marginTop: 20 }}>
            {bullets(copy.before_after).map((point, i) => (
              <div key={i} style={{ background: "#fff", borderRadius: 14, padding: 22, boxShadow: "0 1px 3px rgba(49,46,129,0.1)", color: "#334155", lineHeight: 1.6, fontSize: 16 }}>{point}</div>
            ))}
          </div>
        </div>
      </section>
      <section style={{ maxWidth: 920, margin: "0 auto", padding: "72px 24px" }}>
        <Heading text={lines(copy.tier_comparison)[0] || "Pick your package"} />
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 18, marginTop: 20 }}>
          {bullets(copy.tier_comparison).map((tier, i) => (
            <div key={i} style={{ border: "1px solid #ddd6fe", borderRadius: 16, padding: 24, background: i === 1 ? "#1e1b4b" : "#fff", color: i === 1 ? "#f8fafc" : "#334155", lineHeight: 1.6, fontSize: 16 }}>{tier}</div>
          ))}
        </div>
      </section>
      <section id="start" style={{ background: "#1e1b4b", color: "#f8fafc", padding: "84px 24px", textAlign: "center" }}>
        <div style={{ maxWidth: 680, margin: "0 auto" }}>
          <h2 style={{ fontSize: 30, fontWeight: 800, margin: "0 0 14px" }}>{lines(copy.cta)[0] || "Ready to book the package?"}</h2>
          {lines(copy.cta).slice(1).map((line, i) => (
            <p key={i} style={{ margin: "8px 0", color: "#c7d2fe", lineHeight: 1.7, fontSize: 17 }}>{line.replace(/^- /, "\\u2022 ")}</p>
          ))}
          <a href="mailto:" style={{ display: "inline-block", marginTop: 18, background: "#a78bfa", color: "#1e1b4b", fontWeight: 800, fontSize: 17, padding: "16px 32px", borderRadius: 12, textDecoration: "none" }}>Book this package</a>
        </div>
      </section>
    </main>
  );
}
`;

export const verticalPackTemplate: LandingTemplate = {
  id: "vertical-pack",
  label: "Productized package",
  description: "Hero, a niche problem, a before/after, a tier comparison, and a bundled offer.",
  bestFor: "A productized service sold as set packages a buyer can compare and pick.",
  sections: [
    { key: "hero", kind: "hero", label: "Hero", purpose: "The package promise and who it's for, in one headline and a subhead." },
    { key: "problem", kind: "problem", label: "The problem", purpose: "The specific pain in this niche that the package removes." },
    { key: "before_after", kind: "before_after", label: "Before / after", purpose: "What life looks like before vs. after, as concrete contrasts." },
    { key: "tier_comparison", kind: "tier_comparison", label: "Packages", purpose: "Two or three named tiers with what each includes." },
    { key: "cta", kind: "cta", label: "Call to action", purpose: "A confident close that asks the buyer to pick a package." },
  ],
  defaultCopyPrompts: {
    hero:
      "Write the hero for a productized package. Line 1 is the headline — names the outcome and the niche, under 10 " +
      "words. The lines after are a one-sentence subhead naming the package and who it's for.",
    problem:
      "Write the niche problem. Line 1 is a short headline. The body names the specific, trade-specific pain this " +
      "package removes. 2-3 short lines, in the buyer's words.",
    before_after:
      "Write a before/after. Line 1 is a short headline. Then 3-4 lines, each starting with '- ', each a concrete " +
      "contrast (what it's like now vs. after the package). Specific, not vague.",
    tier_comparison:
      "Write the package tiers. Line 1 is a short headline. Then 2-3 lines, each starting with '- ', one per tier — " +
      "tier name, who it's for, and what's included. Keep each to one line. Never invent prices the owner hasn't set.",
    cta:
      "Write the closing call to action. Line 1 is a short headline asking the buyer to pick a package. The body is " +
      "one or two lines that make choosing easy. Confident, not pushy.",
  },
  componentTemplate: COMPONENT_TEMPLATE,
};
