// build.ts — the Idea Engine auto-build state machine (PA-IDEA-2, Studio+/Enterprise). Stages 4
// (the MVP) and 5 (the sales page) both ship code to the owner's own GitHub + Vercel by reusing the
// shipped Build Tools connectors (github_build, vercel) through the same approval-gated, one-step-
// per-approval pattern the Landing Page Builder proved (lib/landing-pages). We reuse its pure cursor
// logic (nextCursorAfter) and Next.js scaffold (scaffoldFiles) rather than duplicate them.
//
// The build state for a given (idea, build kind) lives in that stage's pa_idea_stage_runs.output:
//   { buildKind, slug, files, cursor, repoFullName, vercelProjectId, deployUrl, githubLogin }
// Each step is staged via stageConnectorAction with the connector payload carrying `idea_id` +
// `idea_build`, so the orchestrator approvals route can advance the build after the step executes
// (mirroring advanceLandingPageBuildAfterApproval). The connector executor zod-strips those two keys;
// the stored pa_action_approvals payload keeps them.

import { stageConnectorAction } from "@/lib/orchestrator/tool-use";
import { nextCursorAfter, scaffoldFiles } from "@/lib/landing-pages/build";
import type { BuildStep } from "@/lib/landing-pages/types";
import { getIdeaById, listStageRuns, updateStageRun, updateIdea } from "./store";
import { writeSnapshotFile, type BrainCtx } from "./snapshot";
import { ideaLog, errMsg } from "./log";
import { latestRunsByStage } from "./store";
import type { StageRunRow } from "./types";

export type IdeaBuildKind = "mvp" | "sales";

/** The pa_idea_stage_runs.output shape for a build stage. */
export type IdeaBuildState = {
  buildKind: IdeaBuildKind;
  slug: string;
  files: Record<string, string>;
  cursor: BuildStep;
  repoFullName: string | null;
  vercelProjectId: string | null;
  deployUrl: string | null;
  githubLogin: string | null;
};

const STAGE_FOR: Record<IdeaBuildKind, number> = { mvp: 4, sales: 5 };

function strField(data: Record<string, unknown>, key: string): string | null {
  const v = data[key];
  return typeof v === "string" && v ? v : null;
}

// ── The connector step for a build cursor (idea-appropriate copy; mirrors landing-pages stagePlanFor) ─

type StepPlan = {
  connector: "github_build" | "vercel";
  action: "create_repo" | "push_files" | "createProject" | "triggerDeploy";
  scopes: readonly string[];
  title: string;
  preview: string;
  payload: Record<string, unknown>;
};

function noun(kind: IdeaBuildKind): string {
  return kind === "mvp" ? "MVP" : "sales page";
}

function stepFor(
  cursor: BuildStep,
  state: IdeaBuildState,
  ideaId: string,
): StepPlan | null {
  const base = { idea_id: ideaId, idea_build: state.buildKind };
  const fileEntries = Object.entries(state.files).map(([path, content]) => ({ path, content }));
  const repo = state.repoFullName ?? state.slug;
  const what = noun(state.buildKind);

  switch (cursor) {
    case "repo":
      return {
        connector: "github_build",
        action: "create_repo",
        scopes: ["github_build"],
        title: `Create the GitHub repo for your ${what} ("${state.slug}")`,
        preview: `Pocket Agent will create a new repository "${state.slug}" on your GitHub account to hold the ${what}'s code.`,
        payload: { name: state.slug, private: true, description: `Idea Engine ${what}: ${state.slug}`, ...base },
      };
    case "push":
      return {
        connector: "github_build",
        action: "push_files",
        scopes: ["github_build"],
        title: `Add the ${what}'s files to "${state.slug}"`,
        preview: `Pocket Agent will commit the generated Next.js project (${fileEntries.length} files) to the repo.`,
        payload: { repo, branch: "main", files: fileEntries, message: `Add ${what} generated by Pocket Agent`, ...base },
      };
    case "project":
      return {
        connector: "vercel",
        action: "createProject",
        scopes: ["vercel"],
        title: `Create the Vercel project for "${state.slug}"`,
        preview: `Pocket Agent will create a Vercel project linked to the "${state.slug}" repo so it can deploy.`,
        payload: {
          name: state.slug,
          framework: "nextjs",
          gitRepo: state.repoFullName ?? (state.githubLogin ? `${state.githubLogin}/${state.slug}` : state.slug),
          ...base,
        },
      };
    case "deploy":
      if (!state.vercelProjectId) return null;
      return {
        connector: "vercel",
        action: "triggerDeploy",
        scopes: ["vercel"],
        title: `Deploy your ${what} ("${state.slug}")`,
        preview: `Pocket Agent will deploy the project so your ${what} goes live at its own URL.`,
        payload: { projectId: state.vercelProjectId, ref: "main", production: true, ...base },
      };
    default:
      return null;
  }
}

// ── Start a build: store the initial state on the run, stage the first step ─────────────────────────

/**
 * Begin a build for one stage run. Writes the build state to the run output, marks it `staged`, and
 * stages the first connector step (create_repo) for owner approval. The MVP/sales files are assembled
 * by the caller (engine.ts) from the blueprint + sales copy.
 */
export async function startIdeaBuild(params: {
  ideaId: string;
  ownerId: string;
  runId: string;
  buildKind: IdeaBuildKind;
  slug: string;
  files: Record<string, string>;
  githubLogin: string | null;
}): Promise<{ ok: true } | { ok: false; error: string }> {
  const state: IdeaBuildState = {
    buildKind: params.buildKind,
    slug: params.slug,
    files: params.files,
    cursor: "repo",
    repoFullName: null,
    vercelProjectId: null,
    deployUrl: null,
    githubLogin: params.githubLogin,
  };
  const step = stepFor("repo", state, params.ideaId);
  if (!step) return { ok: false, error: "Could not plan the first build step." };

  await updateStageRun(params.runId, { status: "staged", output: state as unknown as Record<string, unknown> });

  try {
    await stageConnectorAction({
      userId: params.ownerId,
      subAgentRunId: null,
      connector: step.connector,
      action: step.action,
      payload: step.payload,
      declaredScopes: step.scopes,
      title: step.title,
      preview: step.preview,
      kind: "build_action_approval",
    });
  } catch (e) {
    ideaLog.error("startIdeaBuild stage failed", { ideaId: params.ideaId, error: errMsg(e) });
    return { ok: false, error: errMsg(e) };
  }
  return { ok: true };
}

// ── Advance after an approved build step (called from the approvals route) ──────────────────────────

export type IdeaBuildAdvance =
  | { ok: true; advanced: true; nextCursor: BuildStep }
  | { ok: true; advanced: true; done: true; url: string }
  | { ok: false; status: number; error: string };

/**
 * Find the build (idea, kind) the approved step belongs to, record its artifact, and stage the next
 * step — or, on the terminal deploy, mark the run complete, write the Snapshot build/sales file, and
 * advance the idea. Best-effort: the connector action already executed, so a hiccup here is reported,
 * never undone. The caller passes the stored approval payload (carrying idea_id + idea_build) and the
 * connector executor's result data.
 */
export async function advanceIdeaBuildAfterApproval(params: {
  approvalPayload: Record<string, unknown>;
  ownerId: string;
  action: string;
  data: Record<string, unknown>;
  brain: BrainCtx | null;
}): Promise<IdeaBuildAdvance> {
  const ideaId = typeof params.approvalPayload.idea_id === "string" ? params.approvalPayload.idea_id : null;
  const buildKindRaw = params.approvalPayload.idea_build;
  const buildKind: IdeaBuildKind | null =
    buildKindRaw === "mvp" || buildKindRaw === "sales" ? buildKindRaw : null;
  if (!ideaId || !buildKind) return { ok: false, status: 400, error: "Not an Idea Engine build step." };

  const stage = STAGE_FOR[buildKind];
  const runsRes = await listStageRuns(params.ownerId, ideaId);
  if (!runsRes.ok) return { ok: false, status: runsRes.status, error: runsRes.error };
  const run = latestRunsByStage(runsRes.data).get(stage);
  if (!run) return { ok: false, status: 404, error: "Build run not found." };

  const state = run.output as unknown as IdeaBuildState;
  if (!state || !state.slug) return { ok: false, status: 422, error: "Build run has no state." };

  // Record the artifact this step produced.
  if (params.action === "create_repo") {
    state.repoFullName = strField(params.data, "full_name") ?? state.repoFullName ?? `local/${state.slug}`;
  } else if (params.action === "createProject") {
    state.vercelProjectId = strField(params.data, "projectId") ?? state.vercelProjectId;
  } else if (params.action === "triggerDeploy") {
    state.deployUrl = strField(params.data, "url") ?? `https://${state.slug}.vercel.app`;
  }

  const next = nextCursorAfter(params.action);
  if (!next) return { ok: false, status: 422, error: `Unexpected build action "${params.action}".` };

  // Terminal: deploy done → build is live.
  if (next === "live") {
    state.cursor = "live";
    const url = state.deployUrl ?? `https://${state.slug}.vercel.app`;
    await updateStageRun(run.id, {
      status: "complete",
      output: state as unknown as Record<string, unknown>,
      completed_at: new Date().toISOString(),
    });
    await onBuildComplete(ideaId, params.ownerId, buildKind, state, url, params.brain);
    return { ok: true, advanced: true, done: true, url };
  }

  // Stage the next step.
  state.cursor = next;
  const step = stepFor(next, state, ideaId);
  await updateStageRun(run.id, { status: "staged", output: state as unknown as Record<string, unknown> });
  if (!step) return { ok: false, status: 422, error: `No step for cursor "${next}".` };
  try {
    await stageConnectorAction({
      userId: params.ownerId,
      subAgentRunId: null,
      connector: step.connector,
      action: step.action,
      payload: step.payload,
      declaredScopes: step.scopes,
      title: step.title,
      preview: step.preview,
      kind: "build_action_approval",
    });
  } catch (e) {
    ideaLog.error("advanceIdeaBuild stage failed", { ideaId, error: errMsg(e) });
    return { ok: false, status: 500, error: errMsg(e) };
  }
  return { ok: true, advanced: true, nextCursor: next };
}

// On a finished build, write the Snapshot file and advance the idea's stage (MVP done → ready for
// sales; sales done → ready for launch). The idea's current_stage only moves forward.
async function onBuildComplete(
  ideaId: string,
  ownerId: string,
  buildKind: IdeaBuildKind,
  state: IdeaBuildState,
  url: string,
  brain: BrainCtx | null,
): Promise<void> {
  if (brain) {
    const file = buildKind === "mvp" ? "build.md" : "sales.md";
    const body =
      buildKind === "mvp"
        ? [
            `# Build artifacts`,
            "",
            `**Live MVP:** ${url}`,
            `**GitHub repo:** ${state.repoFullName ?? state.slug}`,
            "",
            "The code is yours, on your accounts. Re-run this stage to rebuild.",
          ].join("\n")
        : [
            `# Sales page`,
            "",
            `**Live sales page:** ${url}`,
            `**GitHub repo:** ${state.repoFullName ?? state.slug}`,
            "",
            "Point your prospects here. The first 25 outreach drafts go out in the Launch stage.",
          ].join("\n");
    await writeSnapshotFile(brain, state.slug, file, body);
  }

  const idea = await getIdeaById(ownerId, ideaId);
  if (idea.ok && idea.data) {
    const reached = buildKind === "mvp" ? 5 : 6;
    if (idea.data.current_stage < reached) {
      await updateIdea(ownerId, ideaId, { current_stage: reached });
    }
  }
}

/** Re-export so the approvals route can detect an Idea Engine build step without importing the engine. */
export function ideaBuildIdOf(payload: Record<string, unknown>): string | null {
  return typeof payload.idea_id === "string" && payload.idea_id ? payload.idea_id : null;
}

export type { StageRunRow };
